---
abstract: 'Perl extension for parsing and validation of DEC and DECS formatted data'
author:
  - 'Tom Kirchner <tk@activestate.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-DEC
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  Parse::Highlife: 0
version: 0.03
