--- #YAML:1.0
name:               Data-DEC
version:            0.02
abstract:           Perl extension for parsing and validation of DEC and DECS formatted data
author:
    - Tom Kirchner <tk@activestate.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:     0
    Parse::Highlife:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
